#!/bin/sh
set -e

case "$1" in
  remove|purge)
    if command -v udevadm >/dev/null 2>&1; then
      udevadm control --reload || true
      udevadm trigger --action=add --subsystem-match=misc --sysname-match=uinput || true
    fi
    ;;
esac

exit 0
